#############################################################################
# Makefile for building: Redstone
# Generated by qmake (2.01a) (Qt 4.8.4) on: Thu Dec 20 21:53:56 2012
# Project:  Redstone.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Redstone.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtSvg -I/usr/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSvg -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		logic/grid.cpp \
		logic/input.cpp \
		logic/cell.cpp \
		logic/wire.cpp \
		logic/output.cpp \
		logic/inverter.cpp \
		logic/gate.cpp \
		logic/clock.cpp \
		logic/flipflop.cpp \
		logic/vector.cpp \
		logic/base.cpp \
		calculator/calculatorwindow.cpp \
		calculator/calculatorengine.cpp \
		calculator/calculatorgridview.cpp \
		utilities/validator.cpp moc_calculatorwindow.cpp \
		moc_calculatorgridview.cpp \
		qrc_svg.cpp
OBJECTS       = main.o \
		grid.o \
		input.o \
		cell.o \
		wire.o \
		output.o \
		inverter.o \
		gate.o \
		clock.o \
		flipflop.o \
		vector.o \
		base.o \
		calculatorwindow.o \
		calculatorengine.o \
		calculatorgridview.o \
		validator.o \
		moc_calculatorwindow.o \
		moc_calculatorgridview.o \
		qrc_svg.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		Redstone.pro
QMAKE_TARGET  = Redstone
DESTDIR       = 
TARGET        = Redstone

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Redstone.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSvg.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile Redstone.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSvg.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Redstone.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Redstone1.0.0 || $(MKDIR) .tmp/Redstone1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Redstone1.0.0/ && $(COPY_FILE) --parents logic/grid.h logic/input.h logic/cell.h logic/wire.h logic/output.h logic/inverter.h logic/gate.h logic/clock.h logic/flipflop.h logic/vector.h logic/base.h calculator/calculatorwindow.h calculator/calculatorengine.h calculator/calculatorgridview.h utilities/validator.h utilities/cispointer.h .tmp/Redstone1.0.0/ && $(COPY_FILE) --parents svg.qrc .tmp/Redstone1.0.0/ && $(COPY_FILE) --parents main.cpp logic/grid.cpp logic/input.cpp logic/cell.cpp logic/wire.cpp logic/output.cpp logic/inverter.cpp logic/gate.cpp logic/clock.cpp logic/flipflop.cpp logic/vector.cpp logic/base.cpp calculator/calculatorwindow.cpp calculator/calculatorengine.cpp calculator/calculatorgridview.cpp utilities/validator.cpp .tmp/Redstone1.0.0/ && (cd `dirname .tmp/Redstone1.0.0` && $(TAR) Redstone1.0.0.tar Redstone1.0.0 && $(COMPRESS) Redstone1.0.0.tar) && $(MOVE) `dirname .tmp/Redstone1.0.0`/Redstone1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Redstone1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_calculatorwindow.cpp moc_calculatorgridview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_calculatorwindow.cpp moc_calculatorgridview.cpp
moc_calculatorwindow.cpp: calculator/calculatorengine.h \
		logic/grid.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h \
		logic/clock.h \
		logic/flipflop.h \
		logic/gate.h \
		logic/input.h \
		logic/inverter.h \
		logic/output.h \
		logic/wire.h \
		utilities/validator.h \
		calculator/calculatorgridview.h \
		calculator/calculatorwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) calculator/calculatorwindow.h -o moc_calculatorwindow.cpp

moc_calculatorgridview.cpp: logic/grid.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h \
		logic/clock.h \
		logic/flipflop.h \
		logic/gate.h \
		logic/input.h \
		logic/inverter.h \
		logic/output.h \
		logic/wire.h \
		utilities/validator.h \
		calculator/calculatorgridview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) calculator/calculatorgridview.h -o moc_calculatorgridview.cpp

compiler_rcc_make_all: qrc_svg.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_svg.cpp
qrc_svg.cpp: svg.qrc \
		resources/Gate-NAND-0.svg \
		resources/Clock-1.svg \
		resources/Gate-XOR-1.svg \
		resources/FlipFlop-1.svg \
		resources/Gate-NOR-0.svg \
		resources/Gate-XNOR-0.svg \
		resources/Gate-AND-1.svg \
		resources/Output-0.svg \
		resources/Inverter-0.svg \
		resources/Gate-OR-0.svg \
		resources/FlipFlop-0.svg \
		resources/Gate-NOR-1.svg \
		resources/Gate-XNOR-1.svg \
		resources/Gate-???-0.svg \
		resources/Input-0.svg \
		resources/Gate-???-1.svg \
		resources/Wire-1.svg \
		resources/Gate-NAND-1.svg \
		resources/Clock-0.svg \
		resources/Gate-XOR-0.svg \
		resources/Input-1.svg \
		resources/Gate-AND-0.svg \
		resources/Output-1.svg \
		resources/Inverter-1.svg \
		resources/Wire-0.svg \
		resources/Gate-OR-1.svg
	/usr/bin/rcc -name svg svg.qrc -o qrc_svg.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp calculator/calculatorwindow.h \
		calculator/calculatorengine.h \
		logic/grid.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h \
		logic/clock.h \
		logic/flipflop.h \
		logic/gate.h \
		logic/input.h \
		logic/inverter.h \
		logic/output.h \
		logic/wire.h \
		utilities/validator.h \
		calculator/calculatorgridview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

grid.o: logic/grid.cpp logic/grid.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h \
		logic/clock.h \
		logic/flipflop.h \
		logic/gate.h \
		logic/input.h \
		logic/inverter.h \
		logic/output.h \
		logic/wire.h \
		utilities/validator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid.o logic/grid.cpp

input.o: logic/input.cpp logic/input.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o input.o logic/input.cpp

cell.o: logic/cell.cpp logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o logic/cell.cpp

wire.o: logic/wire.cpp logic/wire.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wire.o logic/wire.cpp

output.o: logic/output.cpp logic/output.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o output.o logic/output.cpp

inverter.o: logic/inverter.cpp logic/inverter.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inverter.o logic/inverter.cpp

gate.o: logic/gate.cpp logic/gate.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gate.o logic/gate.cpp

clock.o: logic/clock.cpp logic/clock.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clock.o logic/clock.cpp

flipflop.o: logic/flipflop.cpp logic/flipflop.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flipflop.o logic/flipflop.cpp

vector.o: logic/vector.cpp logic/vector.h \
		logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vector.o logic/vector.cpp

base.o: logic/base.cpp logic/base.h \
		utilities/cispointer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o base.o logic/base.cpp

calculatorwindow.o: calculator/calculatorwindow.cpp calculator/calculatorwindow.h \
		calculator/calculatorengine.h \
		logic/grid.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h \
		logic/clock.h \
		logic/flipflop.h \
		logic/gate.h \
		logic/input.h \
		logic/inverter.h \
		logic/output.h \
		logic/wire.h \
		utilities/validator.h \
		calculator/calculatorgridview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculatorwindow.o calculator/calculatorwindow.cpp

calculatorengine.o: calculator/calculatorengine.cpp calculator/calculatorengine.h \
		logic/grid.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h \
		logic/clock.h \
		logic/flipflop.h \
		logic/gate.h \
		logic/input.h \
		logic/inverter.h \
		logic/output.h \
		logic/wire.h \
		utilities/validator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculatorengine.o calculator/calculatorengine.cpp

calculatorgridview.o: calculator/calculatorgridview.cpp calculator/calculatorgridview.h \
		logic/grid.h \
		logic/cell.h \
		logic/vector.h \
		logic/base.h \
		utilities/cispointer.h \
		logic/clock.h \
		logic/flipflop.h \
		logic/gate.h \
		logic/input.h \
		logic/inverter.h \
		logic/output.h \
		logic/wire.h \
		utilities/validator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculatorgridview.o calculator/calculatorgridview.cpp

validator.o: utilities/validator.cpp utilities/validator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o validator.o utilities/validator.cpp

moc_calculatorwindow.o: moc_calculatorwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calculatorwindow.o moc_calculatorwindow.cpp

moc_calculatorgridview.o: moc_calculatorgridview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calculatorgridview.o moc_calculatorgridview.cpp

qrc_svg.o: qrc_svg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_svg.o qrc_svg.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

